[package]
name = "pgn_rater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pgn-reader = "0.26.0"
skillratings = "0.26.0"
thiserror = "1.0.61"
